owncloud/files_pdfviewer

- appinfo/info.xml
So that it looks nicer in the App settings.
Before:
After:
@carlaschroder Please review my English. If you find any mistakes or improvements feel free to directly edit this in this branch.
> Make description little bit more verbose

- controller/displaycontroller.php
- tests/unit/controller/displaycontrollertest.php
Requires https://github.com/owncloud/core/pull/14534
> Whitelist the local domain as child src

- js/previewplugin.js
Fixes https://github.com/owncloud/files_pdfviewer/issues/54
cc @PVince81 :see_no_evil: Inputs?
> Prevent working with IE below 9

- js/previewplugin.js
Backport of #80 
@LukasReschke Please review
> [stable8.2] Add listener for URL change and then close the PDF viewer

- .travis.yml
Also removes HHVM. It's dead baby :fire: :speak_no_evil: 
@MorrisJobke THX
> Use container based infrastructure

- js/previewplugin.js
@MorrisJobke please test. Just try to press the print button in a recent chrome version.
> Allow modals

- appinfo/app.php
- css/style.css
- css/viewer.css
- templates/viewer.php
> [stable8.2] Remove white area below pdf viewer on public page

- controller/displaycontroller.php
- js/workersrc.js
- templates/viewer.php
- tests/unit/controller/displaycontrollertest.php
@MorrisJobke Small security hardening and also adds back the close button
> Add back close button

- appinfo/app.php
- css/style.css
- js/previewplugin.js
fixes #90 
please review @LukasReschke @roha4000 @mhzawadi @brozkeff @fuerst
> Fix regression introduced by 72069f4

- css/style.css
- js/previewplugin.js
> Backport of #91 - Fix regression introduced by 72069f4

- css/style.css
Backport of https://github.com/owncloud/files_pdfviewer/pull/98 to stable8.2
Please review @Henni @LukasReschke @icewind1991 @karlitschek @DeepDiver1975
> [stable8.2] Fix for IE to remove second scrollbar

- tests/bootstrap.php
@DeepDiver1975 let's see if that works
> Add core test namespace

- .travis.yml
add PHP 7.1 and 7.2 to stable10 branch
> add PHP7.2 to stable10 branch

- composer.lock
- tests/unit/bootstrap.php
1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) Update bamarni/composer-bin-plugin (v1.3.0)  (while we are here)
> Php unit 5 to 6

- controller/displaycontroller.php
- js/workersrc.js
- tests/unit/controller/displaycontrollertest.php
Fixes https://github.com/owncloud/enterprise/issues/3377
> Allow opening pdf attachements

- .drone.starlark
- composer.json
- composer.lock
- phpunit.xml
- tests/unit/controller/displaycontrollertest.php
Similar to https://github.com/owncloud/configreport/pull/121
> Adjust tests

- .drone.star
- phpstan.neon
- vendor-bin/phpstan/composer.json
Related - owncloud/QA#642
Update phpstan to 0.12
> [Tests-Only] Update phpstan to latest version

- .drone.star
- vendor-bin/phan/composer.json
Part of https://github.com/owncloud/QA/issues/643
> [Tests-Only] Bump phan 2.7

- CHANGELOG.md
- appinfo/info.xml
Closes https://github.com/owncloud/files_pdfviewer/issues/218
> Merge back Release 0.11.2

- js/previewplugin.js
This is necessary to enable translation texts
> Call the t l10n api for translate the file action's item

- js/previewplugin.js
see https://github.com/owncloud/files_pdfviewer/pull/234#issuecomment-747456930
> Enhance canDownload notification text

- css/viewer.css
> Adjust position of close button

- Makefile
For owncloud-translation-sync composer is not required
> Don't panic on missing composer

- .gitignore
- Makefile
- css/viewer.css
- js/workersrc.js
- l10n/.tx/config
This PR includes commits of the following PRs
https://github.com/owncloud/files_pdfviewer/pull/246 (Fix position of close button)
https://github.com/owncloud/files_pdfviewer/pull/247 (Fix en language shown on de_De locale)
https://github.com/owncloud/files_pdfviewer/pull/248 (Transifex)
https://github.com/owncloud/files_pdfviewer/pull/251 (Transifex)
> Release 0.12.0 2

- css/viewer.css
- img/toolbarButton-secondaryToolbarClose.svg
This will work now on old browsers as well
> make use of vendor zoom icon and transform it

- CHANGELOG.md
- appinfo/info.xml
> Release 0.12.1

- CHANGELOG.md
- appinfo/info.xml
- sonar-project.properties
> Merge back release 0.12.2

- templates/viewer.php
> fix close l10n

- .drone.star
- Makefile
Part of issue https://github.com/owncloud/core/issues/39134
and https://github.com/owncloud/QA/issues/687
> Update .drone.star and drop PHP 7.2 in CI

- .drone.star
- .drone/cancelBuilds.sh
- Makefile
> Backport CI  changes from master branch to release 1.0.0 branch

- js/workersrc.js
Fixes: 
- https://github.com/owncloud/files_pdfviewer/issues/296 
- https://github.com/owncloud/files_pdfviewer/issues/298
> Fix external links not opened in a new tab

- CHANGELOG.md
> Added changed anchor

- .drone.star
- phpunit.xml
- sonar-project.properties
* Skip coverage for PHP 7.3
* Update `phpunit.xml` to match the new structure for PHPUnit 9.5
> [tests-only] Ensure compatibility with PHPUnit v9.5

- composer.json
- composer.lock
This is a development tool that manages the tool dependencies in vendor-bin
- Part of issue: https://github.com/owncloud/QA/issues/749
> Bump bamarni/composer-bin-plugin (1.7.0)

- CHANGELOG.md
- appinfo/info.xml
- sonar-project.properties
> Merge back Release 1.0.2
