owncloud/files_pdfviewer

js/previewplugin.js
templates/viewer.php

With ownCloud 8 the "Close" button of the PDF Viewer is shown incorrectly and overlaps the "secondary tool bar" button  which results in a bad user experience and looks very ugly.
This patch addresses this problem by moving the "Close" button inside the iframe and accessing it using jQuery.
Testplan:
- [ ] Accessing a PDF as logged-in user from the file list works and a Close button is shown.
- [ ] Clicking on the close button closes the file
- [ ] Sharing a single PDF file via link works and no Close button is shown
- [ ] Sharing a folder containing a PDF file via link works and a Close button is shown.
- [ ] Clicking on the close button closes the file
To test this properly you need probably to checkout https://github.com/owncloud/core/pull/14773
cc @PVince81 @nickvergessen Please test

Fix share button display

---

js/previewplugin.js
templates/viewer.php

With ownCloud 8 the "Close" button of the PDF Viewer is shown incorrectly and overlaps the "secondary tool bar" button  which results in a bad user experience and looks very ugly.
This patch addresses this problem by moving the "Close" button inside the iframe and accessing it using jQuery.
Testplan:
- [ ] Accessing a PDF as logged-in user from the file list works and a Close button is shown.
- [ ] Clicking on the close button closes the file
- [ ] Sharing a single PDF file via link works and no Close button is shown
- [ ] Sharing a folder containing a PDF file via link works and a Close button is shown.
- [ ] Clicking on the close button closes the file
cc @PVince81 @nickvergessen Please test.

[stable8] Fix share button display

---

js/previewplugin.js

Hi,
With Firefox (reproduce with versions 31 and 36), we can't download file using download button in PDF.js when Firefox is configure to alway ask on PDF file download. In this case, clicking on download button have no effect and nothing is logged in browser console.
To fix this bug, we add "allow-popups" to iframe's sandbox attribute.

Fix download with Firefox

---

controller/displaycontroller.php
tests/bootstrap.php
tests/unit/controller/displaycontrollertest.php

Fixes https://github.com/owncloud/files_pdfviewer/issues/63 and https://github.com/owncloud/files_pdfviewer/issues/60 and https://github.com/owncloud/files_pdfviewer/issues/66

Whitelist all domains for image

---

js/previewplugin.js

Currently this doesn't only close the pdfviewer but only goes one step further. If you previously browsed to a folder and opened the PDF in there it will close the viewer and go to the parent directory on back button press. This is better than before where the pdfviewer is still open and the content is visible as overlay.
cc @LukasReschke 
@PVince81 Is there a more elegant way to do this?

Add listener for URL change and then close the PDF viewer

---

appinfo/app.php
css/style.css
css/viewer.css
templates/viewer.php

fixes owncloud/core#20557
comment on diff: I moved `style.css` to `viewer.css` and added a new `style.css`
Please review @LukasReschke @PVince81 @owncloud/designers

Remove white area below pdf viewer on public page

---

css/style.css

The fix above is needed to make the footer work in IE. However it introduces a second scrollbar due to the "new" layout configuration.
This fix sets the "display" property back when using the PDF viewer.

Fix for IE to remove second scrollbar

---

js/previewplugin.js

When searching for files using the new tag system and then clicking on a PDF file in the results to see the rendered version in pdf.js, the icons from the search result screen show through. Those search-result icons have a z-index set to 4, while the pdframe created here does not presently have a z-index set (so I believe it defaults to "0"). Setting this to 10 as indicated in this pull-request fixes the issue for me.

z-index on pdframe to avoid bleed-through images

---

js/previewplugin.js
js/workersrc.js
templates/viewer.php

Fixes 
https://github.com/owncloud/files_pdfviewer/issues/116
https://github.com/owncloud/files_pdfviewer/issues/142

Small fixes and improvements

---

CHANGELOG.md
appinfo/info.xml

Note: the tag for v0.8.2 was missing, I didn't bother to go further in the past.

[release-0.9.0] Add changelog with entries for 0.9.0

---

.travis.yml
Makefile

When running `make dist` it told me that the exclusion did not work due to argument order, so I fixed it here.

Fix tar argument order

---

Makefile

So that it is easy to clean the dependencies that get installed in ``vendor`` and ``vendor-bin``

Provide clean-deps Makefile target

---

js/workersrc.js
tests/unit/controller/displaycontrollertest.php

1- Open attachments inside pdf document
2 - Try to close the attachment using the close cross Icon of the files pdfviewer.
Fixes #203 
includes https://github.com/owncloud/files_pdfviewer/pull/200

Bind close button for attachments

---

js/workersrc.js
templates/viewer.php

The character maps are used by pdfjs for font rendering and are needed to properly show some characters. The pdfjs package already provides the needed character maps, but the URL to get them must be correctly set.
Manually: open a pdf document containing Japanese characters through the files_pdfviewer app and check that fonts are correctly displayed.

Fix load of character maps to allow proper rendering of some fonts

---

js/previewplugin.js

In chrome 83 an iframe is not allowed to initiate a download except when the sandbox=allow-downloads attribute is set.
Same as https://github.com/nextcloud/files_pdfviewer/pull/186

Allow Downloads in iframe. Fixes #214

---

js/previewplugin.js

1. Display name is wrong: "favorite"
2. Icon is missing
3. name is not specific and could compete with another app with the same generic name 
Fixes #226

Fix context menu entry

---

phpstan.neon

To avoid getting:
```
php -d zend.enable_gc=0 vendor-bin/phpstan/vendor/bin/phpstan analyse --memory-limit=4G --configuration=./phpstan.neon --no-progress --level=5 appinfo lib
⚠️  You're using a deprecated config option bootstrap. ⚠️️
This option has been replaced with bootstrapFiles which accepts a list of files
to execute before the analysis.
```
I missed doing this in recent  updates of CI infrastructure.

[tests-only] Adjust phpstan.neon bootstrapFiles

---

js/workersrc.js

Issue https://github.com/owncloud/core/issues/38526 hitting the following problem:
In settings -> chaning language to 'Deutsch förmlich (Sie)' will set the locale to de_De. 
PDFJS gets the locale via top html lang attribute and only supports dash locale identifiers for e.G de-De and falls back to english.

fix wrong locale

---

Makefile

Possible fix for "Missing L10N Folder in Marketplace Release"

---

phpunit.xml

This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198

[tests-only][full-ci]Tidy up the phpunit xml file for `files_pdfviewer` app
